/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatItem: typeof import('./src/components/common/ChatItem.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/common/DeleteConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutIndex: typeof import('./src/components/layout/LayoutIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/common/SearchBox.vue')['default']
  }
}
